# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 025a902949afb3472c1905da4719e87def6efb5895ebc7ccede8d022e28514fdf6cdae0ee904d7cd3bcb23e0169a36effacc643fee7bcaf313f73746703b1cd9

test:
  secret_key_base: 5d6be065db41c293fec53c8ed501c97712cb136ed12f308f0a8cf0d3c5dbb403f87275b386f044aec125708288c02ce587ddb00a45b624806a5f724a083b829b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
